site: Van Vu

url: ""
baseurl: ""

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /portfolio/:slug

author:
  name: Van Vu
  image: https://vanvudesign.com/assets/profile.jpg
social:
  name: Van Vu
  links:
    - https://www.instagram.com/pippymaru

plugins:
  - jekyll-seo-tag