basic_settings:
  site_title: Van Vu
  logo_image: /assets/logo.svg
  favicon_image: /assets/favicon.png

menu_settings:
  menu_items:
    - title: 'Portfolio'
      url: '/portfolio'
    - title: 'About'
      url: '/about'


banner_settings:
  title: "Hey, I'm Van Vu"
  description: "A UX designer based out of Italy believing that human-centred design creates meaningful products and services."