basic_settings:
  site_title: Van Vu
  logo_image: /assets/logo.svg
  favicon_image: /assets/favicon.png

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/projects'
    - title: 'About'
      url: '/about'