basic_settings:
  site_title: Van Vu Design
  logo_image: /assets/logo.svg
  favicon_image: /assets/favicon.ico

menu_settings:
  menu_items:
    - title: 'Portfolio'
      url: '/portfolio'
    - title: 'About'
      url: '/about'


banner_settings:
  title: "Hey, I'm Van Vu"
  description: "A UX designer based out of Italy believing that human-centred design creates meaningful products and services."

social_settings:
  instagram_url: 'https://www.instagram.com/pippymaru/'
  dribbble_url: 'https://www.instagram.com/pippymaru/'
  behance_url: 'https://www.instagram.com/pippymaru/'
  linkedin_url: 'https://www.instagram.com/pippymaru/'